language: python
python:
  - '3.7'

before_script:
  - pip install -r requirements.txt

# safelist
branches:
  only:
    - staging

env: DJANGO_SETTINGS_MODULE="pur_beurre.pur_beurre.settings"

services:
  - postgresql

script:
  - pytest